{% set name = "anthropic" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anthropic-{{ version }}.tar.gz
  sha256: f188037c09a86c993196967a7c4ca7b0c30a7f51b261a9360528b5104069c088

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - hatchling
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<2.0.0
    - typing-extensions >=4.1.1,<5
    - anyio >=3.5.0,<4
    - distro >=1.7.0,<2
    - tokenizers >=0.13.0

test:
  imports:
    - anthropic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anthropics/anthropic-sdk-python
  license: MIT
  license_file: LICENSE
  summary: Library for accessing the anthropic API
  doc_url: https://console.anthropic.com/docs

extra:
  recipe-maintainers:
    - jenan-anthropic
    - mikelambert
    - siboehm
    - x5a
