schema_version: 1

context:
  name: anthropic
  version: 1.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/anthropics/anthropic-sdk-python/archive/v${{ version }}.tar.gz
  sha256: 6c39b4173ff606e8f869e88a6edb3fa693edeb66140733c9778fc67ff5c1e41c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - hatch-fancy-pypi-readme
    - hatchling
    - pip
  run:
    - httpx2 >=2.0.0,<3
    - docstring_parser >=0.15,<1
    - typing_extensions >=4.14,<5
    - python >=${{ python_min }},<4.0.0
    - pydantic >=1.9.0,<3
    - anyio >=3.5.0,<5
    - sniffio >=1,<2
    - jiter >=0.4.0,<1
tests:
  - python:
      imports:
        - anthropic
      pip_check: true
      python_version:
        - ${{ python_min }}
        - '*'

about:
  license: MIT
  license_file: LICENSE
  summary: Library for accessing the anthropic API
  homepage: https://github.com/anthropics/anthropic-sdk-python
  documentation: https://console.anthropic.com/docs

extra:
  recipe-maintainers:
    - jan-janssen
    - mikelambert
    - moritzwilksch
    - siboehm
    - x5a
